CRISTAL-244: Clicking outside the text in the navigation tree nodes does nothing
xwiki-contrib/cristal pull request #375
Opened 2024-10-09 10:17 UTC by pjeanjean

# Jira URL

https://jira.xwiki.org/browse/CRISTAL-244

# Changes

## Description

Vuetify's "activation" and Shoelace's "selection" are now fully handled manually to only have a single node selected: the current page (or clicked link if a clickAction is present).
Confusing hover effects have also been disabled.

## Clarifications

In this PR, Vuetify's navigation tree was also made more compact to align a bit more with Shoelace's one.

# Executed Tests

Test suite was run fully.

# Expected merging strategy

* Prefers squash: Yes 
* Backport on branches:
  * N/A

2024-10-09 12:29 UTC, manuelleduc commented
Thanks for working on this @pjeanjean.
First UI related remark: when hovering the node, the cursor becomes a "hand", signaling an action on click.
But, nothing happens unless the click is done on the label.

2024-10-09 12:46 UTC, manuelleduc commented on ds/vuetify/src/vue/x-navigation-tree.vue
> +  href: undefined;
Might worth a comment if the intent is indeed to force href to always be undefined.

2024-10-09 12:46 UTC, manuelleduc commented on ds/vuetify/src/vue/x-navigation-tree.vue
>      activatable
I might be missing something. Isn't just removing this option enough to fix the issue? See https://vuetifyjs.com/en/components/treeview/#activatable

2024-10-09 12:46 UTC, manuelleduc commented on ds/vuetify/src/vue/x-navigation-tree.vue
> +    density="compact"
We do tou change the density? It seems unrelated to the current issue.

2024-10-09 12:46 UTC, manuelleduc commented on ds/vuetify/src/vue/x-navigation-tree.vue
> +:deep(.v-list-item__overlay) {
This deserve a comment.

2024-10-09 12:46 UTC, manuelleduc commented on ds/shoelace/src/vue/x-navigation-tree.vue
> +function updateSelection(id: string) {
General comment on this page changes. Wouldn't it be simpler to not wrap the labels with an a element and to navigate on selection change?

2024-10-09 12:50 UTC, pjeanjean commented on ds/vuetify/src/vue/x-navigation-tree.vue
> +  href: undefined;
Well, the point was to fix [this remark](https://github.com/xwiki-contrib/cristal/pull/375#issuecomment-2402189272), and it seemed to work when I tested it but now I reproduce it again. This seems too inconsistent so I will revert this part and use a CSS rule instead.

2024-10-09 12:51 UTC, pjeanjean commented on ds/vuetify/src/vue/x-navigation-tree.vue
>      activatable
Removing activatable has the side-effect of making non-leaf nodes impossible to activate (no matter the combination of options used), and I want to activate them on page change to display the current page.

2024-10-09 12:54 UTC, pjeanjean commented on ds/shoelace/src/vue/x-navigation-tree.vue
> +function updateSelection(id: string) {
I'm not sure I understand what you are suggesting here.

2024-10-09 13:08 UTC, manuelleduc commented on ds/vuetify/src/vue/x-navigation-tree.vue
> +    density="compact"
Hum, the point of having several design systems is precisely to make them different ;)
We need to discuss this separately with @tkrieck if we want to change it.

2024-10-09 15:33 UTC, pjeanjean commented
Should be fine now.

2024-10-10 09:50 UTC, manuelleduc commented on ds/shoelace/src/vue/x-navigation-tree.vue
> +          updateSelection(item.id);
Looks duplicated with line 151. Wdyt of introducing a common method?

2024-10-10 09:50 UTC, manuelleduc commented on ds/shoelace/src/vue/x-navigation-tree.vue
> +/* Disable hand cursor on items. */
Can you explain *why* we need to disable the hand cursor on item?

2024-10-10 09:50 UTC, manuelleduc commented on ds/shoelace/src/vue/x-navigation-tree.vue
> +    selectedTreeItem!.selected = true;
wdyt of grouping selectedTreeItem and all the methods that are manipulating it in a composable (are at least encapsualte all this)?

2024-10-10 09:50 UTC, manuelleduc commented on ds/vuetify/src/vue/x-navigation-tree.vue
> +<style scoped>
Here too, can you explain also why we need to disable those elements?

2024-10-11 12:47 UTC, manuelleduc requested changes
Two small changes and we are good to merge :)

2024-10-11 12:47 UTC, manuelleduc commented on ds/shoelace/src/utils/navigation-tree-selection.ts
> +import { type Ref } from "vue";
Missing license header

2024-10-11 12:47 UTC, manuelleduc commented on ds/shoelace/src/utils/navigation-tree-selection.ts
> +export class NavigationTreeSelection {
Would be good to have a `since` annotation for traceability and a some javadoc.

2024-10-11 13:43 UTC, merged