CRISTAL-82: Deleting a page is possible
xwiki-contrib/cristal pull request #399
Opened 2024-10-22 14:47 UTC by pjeanjean

# Jira URL

https://jira.xwiki.org/browse/CRISTAL-82

# Changes

## Description

* This adds support for page actions and categories as UI Extensions.
* A basic support to create and display alerts on the UI was also added through the service `AlertsService`.
* The operation `delete(page)` has been implemented for `XWiki`, `Nextcloud` and `FileSystem` backends.
* `PageHierarchyItem` were extended with the property `pageId`, which is useful to list and access parent pages outside of just the breadcrumb.
* The UI now displays a `Manage` category with a `Delete` action as page actions.
* A few components were also improved slightly, e.g., the variant `text` is now usable for buttons.

## Clarifications

This PR ended up bringing a lot of new features to implement the following process:
- A button Delete is available when clicking the 3 vertical dots in page actions
- Clicking the button shows a confirm dialog
- After the deletion is confirmed, the user is redirected to the parent page and an alert notifies him that the page as successfully deleted

While working on this, the login feature was merged to main which made navigation trees noticeably larger.
I noticed that the navigation tree for XWiki did not display more than 15 items at a time because the API used had pagination that was not handled, so this PR also includes a fix for that.

# Screenshots & Video

![image](https://github.com/user-attachments/assets/dea1da4f-e494-4124-be5b-31a932b9906a)
![image](https://github.com/user-attachments/assets/ef470ea1-d558-40b7-bee7-e2d94b4b0d62)
![image](https://github.com/user-attachments/assets/f77c1cb8-bea5-4ff3-b377-991a50a26854)

# Executed Tests

The test suite was run and the features were tested manually.

# Expected merging strategy

* Prefers squash: Yes 
* Backport on branches:
  * N/A

2024-10-22 15:37 UTC, manuelleduc reviewed
First batch of small remarks from a first quick pass.
Also, from testing a running version with the XWiki backend:
- when the user is Guest, deleting the page make the page reload instead of showing an error (because the user does not have delete rights)
- when the user has delete rights, I have a info message but the page isn't actually removed (I get `Authentication failure with login [null]` on XWiki's logs)

2024-10-22 15:37 UTC, manuelleduc commented on api/src/api/storage.ts
> +   * @return a promise on the delete is done
on/when

2024-10-22 15:37 UTC, manuelleduc commented on pnpm-workspace.yaml
> +  - "core/page-actions/*"
This should be one line below, we order the packages by alphabetical order.

2024-10-22 15:37 UTC, manuelleduc commented on core/page-actions/page-actions-ui/src/vue/PageActionsCategory.vue
> +  <x-menu-item v-for="a of actions" :key="a.action.id" :value="a.action.id">
WDYT of renaming 'a' to 'action'?

2024-10-23 14:45 UTC, pjeanjean commented on core/alerts/alerts-ui/src/vue/AlertsToasts.vue
> +        ($event: boolean) => {
This is the behavior of Vue's `update:modelValue`: the only value sent to the listener is the new model's value.

2024-10-23 14:51 UTC, manuelleduc commented on core/alerts/alerts-ui/src/vue/AlertsToasts.vue
> +        ($event: boolean) => {
ok, so maybe `$event` would be better named differently? If I see `$event` I'm always expecting it to have the `Event` type.

2024-10-24 08:53 UTC, manuelleduc commented on ds/shoelace/src/vue/x-alert.vue
>  const variant = computed(() => {
By using [destructuring assignments](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Destructuring_assignment) you can avoid the intermediate `variant` constant and avoid the odd `variant.variant` and `variant.icon` in the template.
```suggestion
const {variant, icon} = computed(() => {
```

2024-10-24 08:53 UTC, pjeanjean commented on ds/shoelace/src/vue/x-alert.vue
>  const variant = computed(() => {
I tried but TypeScript complains when trying to destructure ComputedRefs

2024-10-24 08:55 UTC, manuelleduc requested changes
One small change and we are good to merge.

2024-10-24 08:57 UTC, manuelleduc commented on ds/shoelace/src/vue/x-alert.vue
>  const variant = computed(() => {
ok, there is maybe something to be done with `toRef` but not sure if it would improve readability.
Let's ignore that point for now.

2024-10-24 08:57 UTC, merged